const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Physics,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished
	];
};
self.C3_JsPropNameTable = [
	{BallDeath: 0},
	{BallDeathParticles: 0},
	{BrickHexDeath: 0},
	{DestroyAreaParticles: 0},
	{BallTrailEffect: 0},
	{Sine: 0},
	{BrickHexBlick: 0},
	{Bullet: 0},
	{Physics: 0},
	{Ball: 0},
	{BrickHex: 0},
	{BaseAngle: 0},
	{AngleMultiplier: 0},
	{MoveTo: 0},
	{Pad: 0},
	{DestroyArea: 0},
	{DestroyAreaBg: 0},
	{Solid: 0},
	{Door: 0},
	{Rock: 0},
	{Fade: 0},
	{StartArea: 0},
	{TouchMoveArea: 0},
	{HUD_Finger: 0},
	{HUD_BG: 0},
	{HUD_Wall: 0},
	{Touch: 0},
	{KillAfterAnimation: 0}
];

self.InstanceType = {
	BallDeath: class extends self.ISpriteInstance {},
	BallDeathParticles: class extends self.IParticlesInstance {},
	BrickHexDeath: class extends self.ISpriteInstance {},
	DestroyAreaParticles: class extends self.IParticlesInstance {},
	BallTrailEffect: class extends self.IParticlesInstance {},
	BrickHexBlick: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BrickHex: class extends self.ISpriteInstance {},
	Pad: class extends self.ISpriteInstance {},
	DestroyArea: class extends self.ITiledBackgroundInstance {},
	DestroyAreaBg: class extends self.ITiledBackgroundInstance {},
	Door: class extends self.IWorldInstance {},
	Rock: class extends self.ISpriteInstance {},
	StartArea: class extends self.ISpriteInstance {},
	TouchMoveArea: class extends self.IWorldInstance {},
	HUD_Finger: class extends self.ISpriteInstance {},
	HUD_BG: class extends self.IWorldInstance {},
	HUD_Wall: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	KillAfterAnimation: class extends self.ISpriteInstance {}
}