const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Physics,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.fps
	];
};
self.C3_JsPropNameTable = [
	{BallDeath: 0},
	{BallDeathParticles: 0},
	{BrickHexDeath: 0},
	{DestroyAreaParticles: 0},
	{BallTrailEffect: 0},
	{Sine: 0},
	{BrickHexBlick: 0},
	{BallPusherParticles: 0},
	{Bullet: 0},
	{Physics: 0},
	{MoveTo: 0},
	{Ball: 0},
	{BrickHex: 0},
	{BaseAngle: 0},
	{AngleMultiplier: 0},
	{Pad: 0},
	{DestroyArea: 0},
	{DestroyAreaBg: 0},
	{Solid: 0},
	{DoorNext: 0},
	{Rock: 0},
	{Fade: 0},
	{StartArea: 0},
	{DoorGrey: 0},
	{BallPusher: 0},
	{TouchMoveArea: 0},
	{SpawnArea: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Area0: 0},
	{Area1: 0},
	{Area2: 0},
	{Area3: 0},
	{Area4: 0},
	{Area5: 0},
	{SolidBlock: 0},
	{Wall: 0},
	{HUD_Finger: 0},
	{HUDText: 0},
	{DebugText: 0},
	{BlocksText: 0},
	{LevelText: 0},
	{PointsTexts: 0},
	{FloatingPoints: 0},
	{KillAfterAnimation: 0},
	{Areas: 0},
	{CurrentLevel: 0},
	{CurrentPoints: 0},
	{BallSpeedBase: 0},
	{BallSpeedPerLevel: 0},
	{BricksToDestroy: 0},
	{Index: 0},
	{IndexMax: 0}
];

self.InstanceType = {
	BallDeath: class extends self.ISpriteInstance {},
	BallDeathParticles: class extends self.IParticlesInstance {},
	BrickHexDeath: class extends self.ISpriteInstance {},
	DestroyAreaParticles: class extends self.IParticlesInstance {},
	BallTrailEffect: class extends self.IParticlesInstance {},
	BrickHexBlick: class extends self.ISpriteInstance {},
	BallPusherParticles: class extends self.IParticlesInstance {},
	Ball: class extends self.ISpriteInstance {},
	BrickHex: class extends self.ISpriteInstance {},
	Pad: class extends self.ISpriteInstance {},
	DestroyArea: class extends self.ITiledBackgroundInstance {},
	DestroyAreaBg: class extends self.ITiledBackgroundInstance {},
	DoorNext: class extends self.IWorldInstance {},
	Rock: class extends self.ISpriteInstance {},
	StartArea: class extends self.ISpriteInstance {},
	DoorGrey: class extends self.IWorldInstance {},
	BallPusher: class extends self.ISpriteInstance {},
	TouchMoveArea: class extends self.IWorldInstance {},
	SpawnArea: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Area0: class extends self.ISpriteInstance {},
	Area1: class extends self.ISpriteInstance {},
	Area2: class extends self.ISpriteInstance {},
	Area3: class extends self.ISpriteInstance {},
	Area4: class extends self.ISpriteInstance {},
	Area5: class extends self.ISpriteInstance {},
	SolidBlock: class extends self.IWorldInstance {},
	Wall: class extends self.ISpriteInstance {},
	HUD_Finger: class extends self.ISpriteInstance {},
	HUDText: class extends self.ITextInstance {},
	DebugText: class extends self.ITextInstance {},
	BlocksText: class extends self.ITextInstance {},
	LevelText: class extends self.ITextInstance {},
	PointsTexts: class extends self.ITextInstance {},
	FloatingPoints: class extends self.ITextInstance {},
	KillAfterAnimation: class extends self.ISpriteInstance {},
	Areas: class extends self.ISpriteInstance {}
}