const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Physics,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.wrap,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.ScriptsInEvents.Egameplay_Event2_Act6,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.ScriptsInEvents.Egameplay_Event7_Act1,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{BallDeath: 0},
	{BallDeathParticles: 0},
	{BrickHexDeath: 0},
	{DestroyAreaParticles: 0},
	{BallTrailEffect: 0},
	{Sine: 0},
	{BrickHexBlick: 0},
	{BallPusherParticles: 0},
	{Bullet: 0},
	{Physics: 0},
	{MoveTo: 0},
	{Ball: 0},
	{BrickHex: 0},
	{BaseAngle: 0},
	{AngleMultiplier: 0},
	{Pad: 0},
	{DestroyArea: 0},
	{DestroyAreaBg: 0},
	{Solid: 0},
	{DoorNext: 0},
	{Rock: 0},
	{Fade: 0},
	{StartArea: 0},
	{DoorGrey: 0},
	{BallPusher: 0},
	{PosX: 0},
	{PosY: 0},
	{DragDrop: 0},
	{WallDragH: 0},
	{WallDragHArea: 0},
	{WallAutoMoveH: 0},
	{Sine2: 0},
	{WallAutoMoveCircle: 0},
	{TouchMoveArea: 0},
	{SpawnArea: 0},
	{Keyboard: 0},
	{SafeArea: 0},
	{Area0: 0},
	{Area1: 0},
	{Area2: 0},
	{Area3: 0},
	{Area4: 0},
	{Area5: 0},
	{Area6: 0},
	{Area7: 0},
	{Area8: 0},
	{Area9: 0},
	{Area10: 0},
	{Area11: 0},
	{Area12: 0},
	{Area13: 0},
	{Area14: 0},
	{Area15: 0},
	{StartArea0: 0},
	{StartArea1: 0},
	{StartArea2: 0},
	{StartArea3: 0},
	{StartArea4: 0},
	{StartArea5: 0},
	{StartArea6: 0},
	{Area16: 0},
	{Area17: 0},
	{Area18: 0},
	{Area19: 0},
	{StartArea7: 0},
	{Area20: 0},
	{Area21: 0},
	{Area22: 0},
	{Area23: 0},
	{Area24: 0},
	{Area25: 0},
	{Area26: 0},
	{Area27: 0},
	{SolidBlock: 0},
	{Wall: 0},
	{HUD_Finger: 0},
	{HUDText: 0},
	{DebugText: 0},
	{BlocksText: 0},
	{CurrentLevelText: 0},
	{PointsTexts: 0},
	{FloatingPoints: 0},
	{PauseButton: 0},
	{CoinsText: 0},
	{TotalCoinsText: 0},
	{BestLevelText: 0},
	{BestPointsTexts: 0},
	{PressScale: 0},
	{PressDuration: 0},
	{ResumeButton: 0},
	{QuitButton: 0},
	{MusicButton: 0},
	{SoundsButton: 0},
	{GamePausedHeader: 0},
	{OKButton: 0},
	{SummaryHeader: 0},
	{GameLogo: 0},
	{CoinsIcon: 0},
	{StartButton: 0},
	{LeaderboardButton: 0},
	{LeaderboardButton2: 0},
	{GameVersionText: 0},
	{MoveDistance: 0},
	{Wrap: 0},
	{StarBgLayer1: 0},
	{StarBgLayer2: 0},
	{StarBgLayer3: 0},
	{Browser: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{LocalStorage: 0},
	{KillAfterAnimation: 0},
	{DestroyOutsideLayout: 0},
	{Areas: 0},
	{BgStars: 0},
	{Tween: 0},
	{MenuButtons: 0},
	{GameSounds: 0},
	{GameMusic: 0},
	{BestPoints: 0},
	{BestLevel: 0},
	{TotalCoins: 0},
	{CurrentLevel: 0},
	{CurrentPoints: 0},
	{BallSpeedBase: 0},
	{BallSpeedPerLevel: 0},
	{ColorIndex: 0},
	{BricksToDestroy: 0},
	{GamePaused: 0},
	{Index: 0},
	{IndexMax: 0},
	{StartIndexMax: 0},
	{NewCoins: 0}
];

self.InstanceType = {
	BallDeath: class extends self.ISpriteInstance {},
	BallDeathParticles: class extends self.IParticlesInstance {},
	BrickHexDeath: class extends self.ISpriteInstance {},
	DestroyAreaParticles: class extends self.IParticlesInstance {},
	BallTrailEffect: class extends self.IParticlesInstance {},
	BrickHexBlick: class extends self.ISpriteInstance {},
	BallPusherParticles: class extends self.IParticlesInstance {},
	Ball: class extends self.ISpriteInstance {},
	BrickHex: class extends self.ISpriteInstance {},
	Pad: class extends self.ISpriteInstance {},
	DestroyArea: class extends self.ITiledBackgroundInstance {},
	DestroyAreaBg: class extends self.ITiledBackgroundInstance {},
	DoorNext: class extends self.IWorldInstance {},
	Rock: class extends self.ISpriteInstance {},
	StartArea: class extends self.ISpriteInstance {},
	DoorGrey: class extends self.IWorldInstance {},
	BallPusher: class extends self.ISpriteInstance {},
	WallDragH: class extends self.ISpriteInstance {},
	WallDragHArea: class extends self.ISpriteInstance {},
	WallAutoMoveH: class extends self.ISpriteInstance {},
	WallAutoMoveCircle: class extends self.ISpriteInstance {},
	TouchMoveArea: class extends self.IWorldInstance {},
	SpawnArea: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	SafeArea: class extends self.ITiledBackgroundInstance {},
	Area0: class extends self.ISpriteInstance {},
	Area1: class extends self.ISpriteInstance {},
	Area2: class extends self.ISpriteInstance {},
	Area3: class extends self.ISpriteInstance {},
	Area4: class extends self.ISpriteInstance {},
	Area5: class extends self.ISpriteInstance {},
	Area6: class extends self.ISpriteInstance {},
	Area7: class extends self.ISpriteInstance {},
	Area8: class extends self.ISpriteInstance {},
	Area9: class extends self.ISpriteInstance {},
	Area10: class extends self.ISpriteInstance {},
	Area11: class extends self.ISpriteInstance {},
	Area12: class extends self.ISpriteInstance {},
	Area13: class extends self.ISpriteInstance {},
	Area14: class extends self.ISpriteInstance {},
	Area15: class extends self.ISpriteInstance {},
	StartArea0: class extends self.ISpriteInstance {},
	StartArea1: class extends self.ISpriteInstance {},
	StartArea2: class extends self.ISpriteInstance {},
	StartArea3: class extends self.ISpriteInstance {},
	StartArea4: class extends self.ISpriteInstance {},
	StartArea5: class extends self.ISpriteInstance {},
	StartArea6: class extends self.ISpriteInstance {},
	Area16: class extends self.ISpriteInstance {},
	Area17: class extends self.ISpriteInstance {},
	Area18: class extends self.ISpriteInstance {},
	Area19: class extends self.ISpriteInstance {},
	StartArea7: class extends self.ISpriteInstance {},
	Area20: class extends self.ISpriteInstance {},
	Area21: class extends self.ISpriteInstance {},
	Area22: class extends self.ISpriteInstance {},
	Area23: class extends self.ISpriteInstance {},
	Area24: class extends self.ISpriteInstance {},
	Area25: class extends self.ISpriteInstance {},
	Area26: class extends self.ISpriteInstance {},
	Area27: class extends self.ISpriteInstance {},
	SolidBlock: class extends self.IWorldInstance {},
	Wall: class extends self.ISpriteInstance {},
	HUD_Finger: class extends self.ISpriteInstance {},
	HUDText: class extends self.ITextInstance {},
	DebugText: class extends self.ITextInstance {},
	BlocksText: class extends self.ITextInstance {},
	CurrentLevelText: class extends self.ITextInstance {},
	PointsTexts: class extends self.ITextInstance {},
	FloatingPoints: class extends self.ITextInstance {},
	PauseButton: class extends self.ISpriteInstance {},
	CoinsText: class extends self.ITextInstance {},
	TotalCoinsText: class extends self.ITextInstance {},
	BestLevelText: class extends self.ITextInstance {},
	BestPointsTexts: class extends self.ITextInstance {},
	ResumeButton: class extends self.ISpriteInstance {},
	QuitButton: class extends self.ISpriteInstance {},
	MusicButton: class extends self.ISpriteInstance {},
	SoundsButton: class extends self.ISpriteInstance {},
	GamePausedHeader: class extends self.ISpriteInstance {},
	OKButton: class extends self.ISpriteInstance {},
	SummaryHeader: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	CoinsIcon: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	LeaderboardButton: class extends self.ISpriteInstance {},
	LeaderboardButton2: class extends self.ISpriteInstance {},
	GameVersionText: class extends self.ITextInstance {},
	StarBgLayer1: class extends self.ISpriteInstance {},
	StarBgLayer2: class extends self.ISpriteInstance {},
	StarBgLayer3: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	KillAfterAnimation: class extends self.ISpriteInstance {},
	Areas: class extends self.ISpriteInstance {},
	BgStars: class extends self.ISpriteInstance {},
	MenuButtons: class extends self.ISpriteInstance {}
}